USE health_ai_platform;

-- ============================================================
-- Real policy content for the 5 core Billing knowledge_docs
-- (v1/v2/v3 of each = 15 rows total), replacing the Faker
-- gibberish generated by generate_seed_data.py.
-- ============================================================

-- --- Premium Grace Period Policy -----------------------------
UPDATE knowledge_docs SET content = 'Members receive a 30-day grace period after a missed premium due date before coverage is terminated for non-payment. During the grace period, coverage remains active and claims continue to be processed normally; if payment is not received by the end of the grace period, coverage terminates retroactively to the last paid-through date, and any claims paid during the grace period for services after that date may be subject to recovery. Members receive a grace-period notice at day 1 of delinquency and a second notice at day 20 if payment still has not been received. Members receiving federal subsidy (APTC) are entitled to a 90-day grace period under applicable regulations rather than the standard 30 days.'
WHERE dept_id = 5 AND title = 'Premium Grace Period Policy';

UPDATE knowledge_docs SET content = 'Revision 2 clarifies the claims-recovery process referenced in v1 for subsidized members: during months 2-3 of the 90-day APTC grace period, claims are pended rather than paid, and only released for payment once the member becomes current — this differs from the standard 30-day grace period in v1, where claims continue to pay normally throughout. This revision also adds an auto-reinstatement option: a member whose coverage lapsed for non-payment may reinstate within 15 days of termination by paying the full past-due balance, without needing to go through re-enrollment.'
WHERE dept_id = 5 AND title = 'Premium Grace Period Policy v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds an employer-group variant: for employer-sponsored coverage, the grace period is set by the employer''s group contract (commonly 30 or 60 days) rather than the individual-market default in v1, and delinquency notices are sent to both the employer''s HR/benefits contact and the member directly. This revision also formalizes that partial payment during the grace period extends coverage proportionally rather than requiring full payment to avoid termination, provided the partial payment covers at least the current month''s premium.'
WHERE dept_id = 5 AND title = 'Premium Grace Period Policy v3';

-- --- Payment Plan Eligibility SOP -----------------------------
UPDATE knowledge_docs SET content = 'Members with a past-due balance may request a payment plan rather than paying the full amount at once, provided the balance is under $5,000 and the member has not defaulted on a prior payment plan within the last 12 months. Standard payment plans spread the balance over 3, 6, or 12 months via automatic ACH or payroll deduction — check and credit card payment methods are not eligible for automated payment plans due to processing reliability. A payment plan does not pause the grace period clock referenced in the Premium Grace Period Policy; the member''s coverage remains subject to termination if a scheduled payment plan installment is missed, in addition to the plan being cancelled.'
WHERE dept_id = 5 AND title = 'Payment Plan Eligibility SOP';

UPDATE knowledge_docs SET content = 'Revision 2 raises the balance eligibility threshold in v1 from $5,000 to $8,000 and adds a hardship exception: members who can document financial hardship (job loss, medical emergency) may request a payment plan even with a prior default within the last 12 months, subject to supervisor approval rather than automatic eligibility. This revision also adds a one-time "restart" option: a member whose plan was cancelled for a missed payment may request reinstatement of the same plan (rather than starting over) if they bring the missed installment current within 10 days.'
WHERE dept_id = 5 AND title = 'Payment Plan Eligibility SOP v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds a credit-card eligibility path that v1 and v2 excluded: members may now use credit card for automated payment plan installments if they explicitly acknowledge in writing that a declined card charge counts as a missed payment under the same terms as a failed ACH draft. This revision also shortens the maximum plan length from 12 to 9 months for balances under $2,000, reflecting that smaller balances were found to have unnecessarily long payoff timelines under the original flat 3/6/12-month structure.'
WHERE dept_id = 5 AND title = 'Payment Plan Eligibility SOP v3';

-- --- Write-Off Approval Thresholds -----------------------------
UPDATE knowledge_docs SET content = 'Past-due balances may be written off as uncollectible once standard collection efforts (grace period, two delinquency notices, and one payment plan offer) have been exhausted without resolution, typically 120 days past due. Write-offs under $500 may be approved by a billing specialist directly; write-offs between $500 and $2,500 require billing manager approval; write-offs above $2,500 require finance department sign-off in addition to billing manager approval. A written-off balance is not forgiven — it remains reportable to collections and can be reinstated if the member later re-enrolls with the plan and the balance is still within the applicable statute of limitations.'
WHERE dept_id = 5 AND title = 'Write-Off Approval Thresholds';

UPDATE knowledge_docs SET content = 'Revision 2 lowers the direct billing-specialist approval threshold in v1 from $500 to $250, moving more write-off decisions to manager review after an internal audit found under-scrutinized write-offs concentrated in the $250-500 range. This revision also adds a mandatory documentation requirement: every write-off, regardless of amount, must record which collection efforts in v1''s exhaustion criteria were actually completed (not just "collections attempted"), since audit found generic write-off justifications were common.'
WHERE dept_id = 5 AND title = 'Write-Off Approval Thresholds v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds an expedited path for member death: balances for a deceased member may be written off by a billing specialist regardless of dollar amount once a death certificate or equivalent documentation is on file, bypassing the manager/finance approval tiers in v1 and v2 entirely, since pursuing collection in this circumstance is both operationally unnecessary and reputationally sensitive. This revision also clarifies that write-offs due to plan error (e.g. a billing system miscalculation) are tracked in a separate category from member non-payment write-offs, since they reflect different root causes for reporting purposes.'
WHERE dept_id = 5 AND title = 'Write-Off Approval Thresholds v3';

-- --- Overdue Invoice Escalation SOP -----------------------------
UPDATE knowledge_docs SET content = 'An invoice moves to OVERDUE status when the grace period referenced in the Premium Grace Period Policy expires without payment. At 30 days overdue, the account is flagged for a billing specialist outbound call; at 60 days overdue, a final written notice is sent referencing the specific termination date if unresolved; at 90 days overdue, the account is referred to the write-off review process. Members who contact billing proactively before an escalation step (even after missing the original due date) are not treated as "unresponsive" for escalation-severity purposes — proactive contact pauses the next escalation step pending a resolution conversation.'
WHERE dept_id = 5 AND title = 'Overdue Invoice Escalation SOP';

UPDATE knowledge_docs SET content = 'Revision 2 adds an SMS/text notification channel alongside the written notices in v1, since outbound call attempts at the 30-day mark had a low contact rate — members who have opted into text communications receive a payment reminder at day 15 (before the specialist call) in addition to the existing touchpoints. This revision also adds a "high-value account" fast-track: invoices over $2,000 overdue are escalated to a senior billing specialist at 30 days rather than following the standard queue, given the larger potential loss.'
WHERE dept_id = 5 AND title = 'Overdue Invoice Escalation SOP v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds an explicit do-not-escalate flag for accounts under active dispute (e.g. a member disputing a charge as erroneous): the standard 30/60/90-day escalation clock in v1 pauses while a dispute is open and resumes only after the dispute is resolved, to avoid pursuing collection on a balance the member has formally contested. This revision also requires that every escalation step log the specific outreach method attempted (call, letter, text) and its outcome, not just that escalation occurred, matching the same audit standard applied in Write-Off Approval Thresholds v2.'
WHERE dept_id = 5 AND title = 'Overdue Invoice Escalation SOP v3';

-- --- Refund Processing Guidelines -----------------------------
UPDATE knowledge_docs SET content = 'Overpayments are refunded to the member within 30 days of identification, using the original payment method when possible (ACH reversal, credit card refund) or by check when the original method cannot be reversed. Refunds under $50 may be processed by a billing specialist directly; refunds of $50 or more require a second-person verification before release, to prevent single-person error or fraud. An overpayment is not automatically refunded if the member has any other past-due balance on the account — in that case, the overpayment is first applied to the past-due balance, and only the remaining amount (if any) is refunded, with the member notified of the offset.'
WHERE dept_id = 5 AND title = 'Refund Processing Guidelines';

UPDATE knowledge_docs SET content = 'Revision 2 shortens the standard refund window in v1 from 30 days to 14 days for ACH-reversal-eligible refunds specifically, since the manual check-issuance cases are what actually required the longer window; ACH reversals themselves process much faster. This revision also adds a member-choice option for the past-due-offset scenario in v1: rather than automatically applying the overpayment to a past-due balance, the member may request the full refund with the past-due balance to be handled through the standard collection process instead, provided the request is made before the offset is finalized.'
WHERE dept_id = 5 AND title = 'Refund Processing Guidelines v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds a threshold increase to the second-person verification requirement in v1 and v2: the $50 threshold is raised to $150, reducing verification overhead for the high volume of small-dollar refunds while keeping the control in place for larger amounts. This revision also adds an explicit prohibition on refunding to a different member''s account or payment method than the one that made the original overpayment, even at the member''s request, as a fraud-prevention measure — refund destination must match the original payer''s identity on file.'
WHERE dept_id = 5 AND title = 'Refund Processing Guidelines v3';
