USE health_ai_platform;

-- ============================================================
-- Real policy content for the 5 core Prior Authorization
-- knowledge_docs (v1/v2/v3 of each = 15 rows total), replacing
-- the Faker gibberish generated by generate_seed_data.py.
-- ============================================================

-- --- Prior Auth Turnaround SLA -----------------------------
UPDATE knowledge_docs SET content = 'Standard (routine) prior authorization requests must be decided within 5 business days of receipt of a complete request. Urgent requests — where a standard timeframe could seriously jeopardize the member''s life, health, or ability to regain maximum function — must be decided within 72 hours. Emergency requests involving an immediate threat to life or health must be decided within 24 hours, and may be verbally approved pending written documentation. A request is not considered "received" for SLA purposes until all required clinical documentation is attached; incomplete requests are held in PENDING status with a documented request back to the submitting provider for the missing information, and the SLA clock restarts once the complete package is received.'
WHERE dept_id = 2 AND title = 'Prior Auth Turnaround SLA';

UPDATE knowledge_docs SET content = 'Revision 2 clarifies "business day" for SLA purposes in v1 as excluding weekends and the plan''s recognized holidays, and adds an escalation trigger: any routine request approaching the 5-day SLA without a reviewer assigned is automatically escalated to the review queue supervisor at the 4-day mark. This revision also introduces a distinct SLA for imaging and DME requests specifically (3 business days instead of 5), since these categories have historically shown the highest rate of unnecessary delay.'
WHERE dept_id = 2 AND title = 'Prior Auth Turnaround SLA v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds a peer-to-peer stopwatch pause: when a provider requests a peer-to-peer review (see Peer-to-Peer Review Guidelines), the SLA clock pauses from the request until the call is completed or 2 business days pass, whichever comes first, at which point the clock resumes automatically even if the provider has not responded. This prevents providers from indefinitely extending a denial window by requesting but never scheduling a peer-to-peer call.'
WHERE dept_id = 2 AND title = 'Prior Auth Turnaround SLA v3';

-- --- Urgent PA Escalation SOP -----------------------------
UPDATE knowledge_docs SET content = 'A prior authorization request is classified URGENT when the requesting provider indicates, in writing, that the standard timeframe could seriously jeopardize the member''s life or health, or could subject the member to severe pain that cannot be managed without the requested care. Urgent classification is accepted at face value from the provider — reviewers do not second-guess the urgency designation itself, only the medical necessity of the underlying request. Urgent requests are routed directly to an on-call reviewer rather than the standard queue, and the requesting provider is notified of receipt within 1 hour via the provider portal or, if unavailable, by phone.'
WHERE dept_id = 2 AND title = 'Urgent PA Escalation SOP';

UPDATE knowledge_docs SET content = 'Revision 2 adds an after-hours escalation path: urgent requests submitted outside business hours page the on-call medical director directly rather than waiting for the next business day, given the 72-hour SLA in the Turnaround SLA policy applies regardless of when the clock starts. This revision also requires that any urgent request downgraded to routine after clinical review include a documented rationale visible to the submitting provider, since urgency downgrades are a common source of provider appeals.'
WHERE dept_id = 2 AND title = 'Urgent PA Escalation SOP v2';

UPDATE knowledge_docs SET content = 'Revision 3 formalizes the emergency (24-hour) tier referenced in the Turnaround SLA policy as a distinct escalation path from standard urgent requests: emergency requests may be verbally approved by the on-call medical director with written documentation to follow within 24 hours, and are logged separately for compliance reporting given the abbreviated review standard. This revision also clarifies that emergency approvals do not waive medical necessity review — a retrospective review is still completed within 5 business days of the verbal approval.'
WHERE dept_id = 2 AND title = 'Urgent PA Escalation SOP v3';

-- --- Medical Necessity Criteria - Imaging -----------------------------
UPDATE knowledge_docs SET content = 'Advanced imaging (MRI, CT, PET) requires prior authorization except when ordered from an emergency department or during an inpatient stay. Requests must include the specific clinical indication, relevant conservative treatment already attempted (e.g. 6 weeks of physical therapy for non-traumatic musculoskeletal complaints, where applicable), and any relevant prior imaging results. Standard X-ray and ultrasound do not require prior authorization. Requests lacking a specific clinical indication (e.g. "rule out pathology" with no supporting symptoms) are returned to the provider for clarification rather than denied outright, since this is typically a documentation gap rather than a lack of medical necessity.'
WHERE dept_id = 2 AND title = 'Medical Necessity Criteria - Imaging';

UPDATE knowledge_docs SET content = 'Revision 2 adds condition-specific criteria referenced from nationally recognized clinical guidelines (e.g. ACR Appropriateness Criteria) as the default basis for imaging medical necessity review, superseding case-by-case reviewer judgment except where the requesting provider furnishes evidence the member''s presentation falls outside the standard guideline (e.g. atypical presentation, red-flag symptoms). This revision also exempts oncology staging and surveillance imaging from the standard conservative-treatment documentation requirement in v1, since it is not clinically applicable to cancer care.'
WHERE dept_id = 2 AND title = 'Medical Necessity Criteria - Imaging v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds a repeat-imaging threshold: a second advanced imaging study of the same body region within 90 days requires an explicit clinical justification for why the prior study was insufficient (not simply a repeat order), to reduce unnecessary duplicate imaging. This revision also lowers the pediatric threshold for automatic approval without full guideline review for certain indications, reflecting that radiation exposure concerns in pediatric populations often justify imaging that would not meet adult criteria.'
WHERE dept_id = 2 AND title = 'Medical Necessity Criteria - Imaging v3';

-- --- Peer-to-Peer Review Guidelines -----------------------------
UPDATE knowledge_docs SET content = 'Before or in lieu of filing a formal appeal, a treating provider may request a peer-to-peer conversation with the plan''s reviewing physician to discuss a denial or pending determination. Peer-to-peer requests must be scheduled within 3 business days of the denial notice and are limited to a single call per determination unless new clinical information becomes available. The reviewing physician on the call must hold an active license in a relevant specialty area, though not necessarily the same specialty as the requesting provider. The outcome of the call (upheld, overturned, or additional information requested) is documented in the PA record regardless of outcome.'
WHERE dept_id = 2 AND title = 'Peer-to-Peer Review Guidelines';

UPDATE knowledge_docs SET content = 'Revision 2 adds a same-day option for urgent-classification denials: rather than the standard 3-business-day scheduling window in v1, urgent PA denials may request a peer-to-peer call for the same or next business day, reflecting the compressed clinical timeline. This revision also clarifies that a peer-to-peer call resulting in an overturned denial does not require a separate formal appeal — the reviewing physician''s verbal overturn is binding and is documented as the final determination directly.'
WHERE dept_id = 2 AND title = 'Peer-to-Peer Review Guidelines v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds a documentation standard for the call itself: the reviewing physician must document the specific clinical rationale discussed, not just the outcome, since peer-to-peer call summaries are frequently referenced in subsequent external appeals. This revision also permits the requesting provider to designate a covering colleague to take the call on their behalf when the original ordering provider is unavailable within the scheduling window, provided the covering colleague has direct knowledge of the case.'
WHERE dept_id = 2 AND title = 'Peer-to-Peer Review Guidelines v3';

-- --- PA Denial Letter Requirements -----------------------------
UPDATE knowledge_docs SET content = 'Every prior authorization denial letter must include: the specific service or item denied, the specific clinical criteria or guideline the request failed to meet (not a generic "not medically necessary"), the name and credentials of the reviewing clinician, and clear instructions for both the standard appeal process and the peer-to-peer review option, including relevant deadlines for each. Denial letters must be sent to both the member and the ordering provider within 1 business day of the determination. Letters using internal rule codes or adjudication shorthand without a plain-language explanation do not meet this standard and must be corrected before sending.'
WHERE dept_id = 2 AND title = 'PA Denial Letter Requirements';

UPDATE knowledge_docs SET content = 'Revision 2 adds a requirement to cite the specific clinical guideline or literature reference used in the determination (e.g. the exact ACR Appropriateness Criteria section), not just that "guidelines were applied," so both the member and provider can independently review the standard used. This revision also requires denial letters for imaging-specific determinations to reference the Medical Necessity Criteria - Imaging policy explicitly, given imaging is the highest-volume denial category.'
WHERE dept_id = 2 AND title = 'PA Denial Letter Requirements v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds accessibility and language-access requirements matching those adopted for Claims EOBs: denial letters must be available in the member''s preferred language on file and in large-print or screen-reader-compatible formats on request. This revision also requires that partial-approval determinations (PARTIAL status) use the same plain-language and citation standards as full denials for the portion of the request that was not approved, rather than treating partial approvals as exempt from the denial-letter requirements.'
WHERE dept_id = 2 AND title = 'PA Denial Letter Requirements v3';
