USE health_ai_platform;

-- ============================================================
-- Real policy content for the 5 core Claims knowledge_docs
-- (v1/v2/v3 of each = 15 rows total), replacing the Faker
-- gibberish generated by generate_seed_data.py. Content is
-- realistic fictional policy text, written to actually answer
-- the kinds of questions the chatbot's policy_question intent
-- is meant to handle.
-- ============================================================

-- --- Claims Timely Filing Policy -----------------------------
UPDATE knowledge_docs SET content = 'All claims must be submitted within 180 calendar days of the date of service. Claims submitted after this window will be denied for timely filing unless one of the following exceptions applies: (1) the member was retroactively enrolled and the plan notified the provider of eligibility after the 180-day window had already passed, (2) coordination of benefits with a primary payer delayed submission and the claim is submitted within 90 days of the primary payer''s final determination, or (3) a documented system outage on the payer''s end prevented electronic submission. Providers requesting a timely filing exception must submit supporting documentation (EOB from the primary payer, enrollment correspondence, or outage notice) alongside the claim. Claims denied for timely filing may be appealed through the standard Claims Appeals Process within 60 days of the denial notice.'
WHERE dept_id = 1 AND title = 'Claims Timely Filing Policy';

UPDATE knowledge_docs SET content = 'Revision 2 of the Timely Filing Policy clarifies the 180-day standard filing window introduced in v1 and adds guidance for electronic vs. paper submissions: electronic claims are considered "submitted" on the date accepted by the clearinghouse (not the date transmitted), while paper claims use the postmark date. Corrected claims resubmitted after an initial timely rejection retain the original submission date for timely filing purposes, provided the correction is submitted within 30 days of the rejection notice. This revision also extends the retroactive-enrollment exception in v1 from 60 to 90 days to align with standard COB resolution timelines.'
WHERE dept_id = 1 AND title = 'Claims Timely Filing Policy v2';

UPDATE knowledge_docs SET content = 'Revision 3 of the Timely Filing Policy adds a network-status carve-out: out-of-network providers are held to a 365-day filing window instead of the standard 180 days, reflecting that OON providers may not have real-time eligibility verification access. It also formalizes the appeal path referenced in v1 — timely filing denials must be appealed in writing within 60 days and must include proof of timely submission (clearinghouse acceptance log, certified mail receipt, or fax confirmation). Appeals lacking proof of timely submission will be upheld without further clinical review.'
WHERE dept_id = 1 AND title = 'Claims Timely Filing Policy v3';

-- --- Duplicate Claim Handling SOP -----------------------------
UPDATE knowledge_docs SET content = 'A claim is flagged as a potential duplicate when it matches an existing claim on member ID, provider ID, date of service, and CPT code. Flagged claims are held in a PENDED status pending adjudicator review rather than auto-denied. The adjudicator must confirm whether the second submission represents (a) a true duplicate (same service, same encounter) — deny with reason "Duplicate claim" and reference the original claim number, (b) a corrected claim (same encounter, different billed amount or code) — process as a correction and void the original, or (c) a legitimately separate encounter that happens to share the same date and CPT code (e.g. two visits in one day) — release the pend and process both claims normally. Adjudicators must document their determination in the claim notes regardless of outcome.'
WHERE dept_id = 1 AND title = 'Duplicate Claim Handling SOP';

UPDATE knowledge_docs SET content = 'Revision 2 tightens the duplicate-matching logic from v1 by adding a $0.01 billed-amount tolerance and a same-provider-NPI requirement, reducing false-positive duplicate holds when a provider bills under multiple tax IDs for the same NPI. It also introduces a 48-hour auto-release: if a pended duplicate is not reviewed by an adjudicator within 48 hours, it is automatically released for standard processing rather than remaining indefinitely pended, with a flag left on the claim for post-payment audit.'
WHERE dept_id = 1 AND title = 'Duplicate Claim Handling SOP v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds explicit guidance for recurring/series claims (e.g. physical therapy, dialysis) that legitimately share member, provider, and CPT code across many dates: these are exempted from the standard duplicate match entirely and instead validated against the associated prior authorization''s approved visit count. It also requires adjudicators to notify the billing provider when a true duplicate is denied, rather than silently denying, to reduce repeat duplicate submissions from the same office.'
WHERE dept_id = 1 AND title = 'Duplicate Claim Handling SOP v3';

-- --- COB Determination Guide -----------------------------
UPDATE knowledge_docs SET content = 'When a member has coverage under more than one health plan, this plan''s payment order is determined using the standard birthday rule for dependents (the parent whose birthday falls earlier in the calendar year is primary) and the "employee plan is primary over retiree/COBRA plan" rule for subscribers with multiple active plans. Claims should be submitted to the primary payer first; this plan will process as secondary using the primary payer''s Explanation of Benefits (EOB) to calculate any remaining member liability, never exceeding what this plan would have paid as primary. Claims submitted without a primary payer EOB when COB is on file for the member will be pended, not denied, with a request sent to the provider for the missing EOB.'
WHERE dept_id = 1 AND title = 'COB Determination Guide';

UPDATE knowledge_docs SET content = 'Revision 2 adds Medicare-specific COB rules: for members with both this plan and Medicare, this plan is primary only if the employer group has fewer than 20 employees (small group) or the member qualifies under a documented Medicare Secondary Payer exception; otherwise Medicare is primary regardless of the birthday rule in v1. It also clarifies that court-ordered coverage (e.g. divorce decrees naming a specific parent''s plan as primary for a dependent) overrides the standard birthday rule when a copy of the order is on file.'
WHERE dept_id = 1 AND title = 'COB Determination Guide v2';

UPDATE knowledge_docs SET content = 'Revision 3 formalizes the COB data refresh cycle: member COB status is re-verified annually and whenever a claim indicates a change (e.g. a new EOB from a payer not currently on file). It also adds a non-duplication clause for members with two active employer plans of equal seniority — in the absence of a clear primary, benefits are prorated 50/50 between the two payers rather than defaulting either plan to full primary liability.'
WHERE dept_id = 1 AND title = 'COB Determination Guide v3';

-- --- Claims Appeals Process -----------------------------
UPDATE knowledge_docs SET content = 'Members and providers may appeal a denied or partially paid claim within 180 days of the denial notice. A first-level appeal is reviewed by an adjudicator who was not involved in the original decision and must be resolved within 30 calendar days for standard claims or 72 hours for urgent/expedited appeals involving ongoing treatment. If the first-level appeal is denied, the appellant may request a second-level appeal, which is reviewed by a physician advisor for any claim involving a medical necessity determination. Appeals must include: the original claim number, the specific reason for disagreement, and any new supporting documentation not previously submitted (medical records, itemized bills, or a letter of medical necessity).'
WHERE dept_id = 1 AND title = 'Claims Appeals Process';

UPDATE knowledge_docs SET content = 'Revision 2 adds a peer-to-peer review option to the appeals process in v1: for medical necessity denials, the treating provider may request a direct phone conversation with the plan''s reviewing physician before or instead of filing a formal second-level appeal. This revision also shortens the standard first-level appeal turnaround from 30 to 15 business days when the appeal is submitted through the provider portal rather than by mail.'
WHERE dept_id = 1 AND title = 'Claims Appeals Process v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds an external review option: if a second-level internal appeal (per v1) is denied and the denial is based on medical necessity or experimental/investigational determination, the member may request an Independent External Review by an accredited third-party organization within 4 months of the internal appeal denial. The plan''s decision is binding only if the external reviewer upholds it; an external reviewer overturning the denial obligates the plan to pay the claim within 5 business days of the external decision.'
WHERE dept_id = 1 AND title = 'Claims Appeals Process v3';

-- --- EOB Generation Standards -----------------------------
UPDATE knowledge_docs SET content = 'Every adjudicated claim generates an Explanation of Benefits (EOB) within 5 business days of the final determination. Each EOB must include: the claim number, date of service, billed amount, allowed amount, amount paid, member responsibility (deductible, copay, and coinsurance shown separately), and — for any denied or partially paid line — a plain-language denial reason with the corresponding appeal-rights language. EOBs are delivered electronically by default to members enrolled in paperless communications and by mail otherwise; a duplicate EOB may be requested by the member or provider at any time through the portal or by calling Member Services.'
WHERE dept_id = 1 AND title = 'EOB Generation Standards';

UPDATE knowledge_docs SET content = 'Revision 2 adds a consolidated EOB option: for members with multiple claims processed in the same batch cycle, a single consolidated EOB may be generated instead of one per claim, provided each claim''s line-item detail from v1 remains fully itemized within the consolidated document. This revision also requires that any EOB reflecting a COB secondary-payment calculation explicitly show the primary payer''s allowed amount alongside this plan''s calculation, to reduce member confusion about how the secondary payment was derived.'
WHERE dept_id = 1 AND title = 'EOB Generation Standards v2';

UPDATE knowledge_docs SET content = 'Revision 3 adds accessibility requirements: EOBs must be available in large-print and screen-reader-compatible formats on request at no charge, and the plain-language denial reason required in v1 must avoid internal adjudication rule codes (e.g. "Rule 4b applied") in favor of a member-facing explanation. This revision also shortens the generation window from 5 business days to 3 business days for any claim tied to an active prior authorization, since those members are more likely to need the EOB for continuity-of-care decisions.'
WHERE dept_id = 1 AND title = 'EOB Generation Standards v3';